### ISSUE TITLE
What value should REDIS_CLUSTER_URLS actually be?

### ISSUE THREAD

**Issue by HappyZombies** [brunojppb/redis-cluster-demo#1]
Hey there, following your blog post and this repo and I am so close to getting it running! But what should be REDIS_CLUSTER_URLS be? I set it to the IPs we configured 

```
173.18.0.2:6379
  173.18.0.3:6379 
  173.18.0.4:6379
  173.18.0.5:6379
  173.18.0.6:6379
 173.18.0.7:6379
```

But i am unable to connect at all, i get timeouts errors. What does your .env file look like for this environment variable?

**Comment by brunojppb** [comment]
Hey @HappyZombies good question.
The IP addresses are only meant for the redis cluster setup here:
https://github.com/brunojppb/redis-cluster-demo/blob/151a8703f2f0237fd4328944535806f41b56cf49/redis/entrypoint.sh#L13-L20

But what you really need to pass to your Express server is the host names created in our `docker-compose` file here:
https://github.com/brunojppb/redis-cluster-demo/blob/151a8703f2f0237fd4328944535806f41b56cf49/docker-compose.yml#L22

As you can see, it's just one long string with the combination of `host:port` and the client implementation is breaking it apart here:
https://github.com/brunojppb/redis-cluster-demo/blob/151a8703f2f0237fd4328944535806f41b56cf49/src/service/redisClient.js#L10-L15

I'm not sure how is your setup is done. Perhaps you are not using `docker-compose` to spin-up your express server as well? Otherwise, if you are running your app directly with `node index.js`, it won't be able to reach the Redis containers running via Docker as those host names are bound to the docker-compose setup network.

**Comment by HappyZombies** [comment]
Ah yes, the latter was exactly why this wasn't working for me...it's cuz I was running `node index.js`. Thanks for helping me out! The reason I ran `node index.js` was because I wanted to use the VSCode debugger to step through the express app and see it connect to the Redis Clusters.

Forgive as my Docker knowledge isn't all there, but if I want to accomplish this, I simply should just map the ports right? So I have this (and uh, I am still not able to connect).

```yml

  redis_1:
    image: 'redis:latest'
    container_name: redis_1
    ports:
      - "6379:6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.2

  redis_2:
    image: 'redis:latest'
    container_name: redis_2
    ports:
      - "9000:6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.3
 ```
And so on. Or do I need to do something else? (I understand at this point it's out of scope for your project and blog, so I appreciate all the help this project and your blog has done for me :). Thanks!)
